name: CI-feature-branch
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: ["*", "!main", "!master", "!skip/*"]
  workflow_dispatch:
jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: oidc
        run: |
          npm install
      - name: Build
        working-directory: oidc
        run: |
          npm run build
      - name: Test
        working-directory: oidc
        run: |
          npm test
