name: CI-feature-branch
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: ["*", "!main", "!master", "!skip/*"]
  workflow_dispatch:
jobs:
  test-provider-aripalo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: provider-aripalo
        run: |
          npm install
      - name: Build
        working-directory: provider-aripalo
        run: |
          npm run build
      - name: Test
        working-directory: provider-aripalo
        run: |
          npm test
  test-provider-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: provider-cfn
        run: |
          npm install
      - name: Build
        working-directory: provider-cfn
        run: |
          npm run build
      - name: Test
        working-directory: provider-cfn
        run: |
          npm test
  test-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: tools
        run: |
          npm install
      - name: Test
        working-directory: tools
        run: |
          npm test
