name: set-up-oidc
concurrency: ci-${{ github.ref }}
on:
  workflow_dispatch:
jobs:
  account-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Identify account and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          EXPECTED_ACCOUNT_ID: ${{ vars.DEV_AWS_ACCOUNT_ID }}
        working-directory: oidc
        run: |
          npm run account-check
  set-up-oidc:
    runs-on: ubuntu-latest
    needs: [account-check]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: oidc
        run: |
          npm install
      - name: Build
        working-directory: oidc
        run: |
          npm run build
      - name: Test
        working-directory: oidc
        run: |
          npm test
      