name: set-up-oidc
concurrency: ci-${{ github.ref }}
on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_session_token:
        required: true
      aws_default_region:
        default: us-east-1
      expected_account_id:
        required: true
jobs:
  use_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Use the inputs
        env:
          SOME_INPUT: ${{ inputs.expected_account_id }}
          SOME_GITHUB_EVENT_INPUT: ${{ github.event.inputs.expected_account_id }}
        run: |
          echo "the expected account id is ${SOME_INPUT}"
          echo "it is also ${SOME_GITHUB_EVENT_INPUT}"
  account-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mask secret inputs
        run: |
          echo "::add-mask::${{ github.event.inputs.aws_access_key_id}}"
          echo "::add-mask::${{ github.event.inputs.aws_secret_access_key }}"
          echo "::add-mask::${{ github.event.inputs.aws_session_token }}"
          echo "::add-mask::${{ github.event.inputs.aws_default_region }}"
          echo "::add-mask::${{ github.event.inputs.expected_account_id }}"
      - name: Identify account and region
        working-directory: oidc
        run: |
          AWS_ACCESS_KEY_ID=${{ github.event.inputs.aws_access_key_id}} \
          AWS_SECRET_ACCESS_KEY=${{ github.event.inputs.aws_secret_access_key }} \
          AWS_SESSION_TOKEN=${{ github.event.inputs.aws_session_token }} \
          AWS_DEFAULT_REGION=${{ github.event.inputs.aws_default_region }} \
          EXPECTED_ACCOUNT_ID=${{ github.event.inputs.expected_account_id }} \
          npm run account-check
  deploy-provider:
    runs-on: ubuntu-latest
    needs: [account-check]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: oidc
        run: |
          npm install
      - name: Build
        working-directory: oidc
        run: |
          npm run build
      - name: Test
        working-directory: oidc
        run: |
          npm test
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        working-directory: oidc
        run: |
          npm run deploy
